### ISSUE TITLE
PDFFixedDocument SerialNumber is missing

### ISSUE THREAD

**Issue by sktdeepak** [o2solutions/pdf4net#1]
In .net core app,

we are migrating Version 4.7.0 to 10.3.2

As per newer version `PDFDocument` to `PDFFixedDocument`, so in older version we have `SerialNumber` property in `PDFDocument` but in newerversion `PDFFixedDocument` does not contain `SerialNumber` parameter.

Please help to resolve this issue.

Thanks!

**Comment by thepirat000** [comment]
Same problem here

**Comment by ipdfdev** [comment]
PDF4NET 10 no longer uses a serial number for unlocking the evaluation version. The commercial assemblies are different from the evaluation ones and they are already unlocked.
