### ISSUE TITLE
Problem in ExtractWords output

### ISSUE THREAD

**Issue by hojjatnikan** [o2solutions/pdf4net#10]
I have encountered another issue with the `ExtractWords` method. There are two main problems:

1. The number of words detected varies each time. For example, the same PDF file might return 20 words once, 15 words another time, and 25 words on another attempt.
2. The method inconsistently detects text on the page. Sometimes it correctly identifies a word and outputs it, but other times it misidentifies the same word. This issue also occurs with numbers. For instance, the number 131 is sometimes correctly identified as 131, but other times it is misidentified as 1A3.

**Comment by pdf4dev-solutions-support** [comment]
The evaluation version of PDF4NET replaces random characters from extracted text with letters from PDF4NET word. This causes both behaviors you encountered.

**Comment by hojjatnikan** [comment]
Thank you for the clarification regarding the evaluation version of PDF4NET.

**Comment by hojjatnikan** [comment]
Thank you for the clarification regarding the evaluation version of PDF4NET.
