### ISSUE TITLE
Cannot use DrawImage

### ISSUE THREAD

**Issue by xale76** [o2solutions/pdf4net#4]
Hello I have dll version 4.4.1
If I try this simple program

Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Dim doc As New PDFDocument()
        ' Serial number goes here
        doc.SerialNumber = "my serial number"
        Dim pg As New PDFPage
        Dim brush As New PDFBrush
        Dim jpeg As New PDFJpegImage("c:\tmp\new-pm-logo.jpg")
        pg.Canvas.DrawImage(jpeg, 3, 90, jpeg.Width, jpeg.Height)
        doc.Pages.Add(pg)
        doc.Save("c:\tmp\test.pdf")
 End Sub
I got error at DrawImage => Object reference not set to an instance of an object

What's happening? I tried to update with nuget but newest version are completely different from that one that I use (of course this snippet of code is an example) so I can move to newest. Please help me

**Comment by pdf4dev-solutions-support** [comment]
Please attach the image (new-pm-logo.jpg) and we'll investigate the problem.

**Comment by xale76** [comment]
I fixed. the problem was 
dim pg as new PDFPage.
it works if I write dim pg as PDFPage=doc.addPage

**Comment by pdf4dev-solutions-support** [comment]
The page must be included in a document before adding content to it. If you move the line
`doc.Pages.Add(pg)`
before 
`pg.Canvas.DrawImage(jpeg, 3, 90, jpeg.Width, jpeg.Height)`
it will also work.
