### ISSUE TITLE
MergeFiles watermark

### ISSUE THREAD

**Issue by tylermmurphy** [o2solutions/pdf4net#6]
In previous versions when using the evaluation, there would be a watermark on the pages. Once we applied the SerialNumber, the watermark was gone. I recently downloading the nuget package for .NET.  I do not see any way to remove the watermarks. Is this no longer an option?

**Comment by pdf4dev-solutions-support** [comment]
The nuget packages on nuget.org are evaluation only, they cannot be unlocked. The commercial nuget packages are unlocked and they no longer require a serial number.
