### ISSUE TITLE
Extracting text from pdf is not working that well

### ISSUE THREAD

**Issue by FlipEX** [o2solutions/pdf4net#8]
Hi,

I am trying to extract all the text from a pdf using this code:

```
public static string ExtractTextFromPdf(string pdfFilePath)
{
    var stream = File.OpenRead(pdfFilePath);
    PDFFixedDocument pdfDocument = new PDFFixedDocument(stream);
    StringBuilder pdfText = new StringBuilder();

    for (int i = 0; i < pdfDocument.Pages.Count; i++)
    {
        PDFPage pdfPage = pdfDocument.Pages[i];
        PDFContentExtractionContext context = new PDFContentExtractionContext();
        PDFContentExtractor contentExtractor = new PDFContentExtractor(pdfPage);
        pdfText.AppendLine(contentExtractor.ExtractText(context));
    }

    return pdfText.ToString();
}
```

The problem is that the text i not correct (I have marked a few places).
![text_output](https://github.com/o2solutions/pdf4net/assets/3669438/ebebe6ee-4f1a-4bb9-9db0-edff3a22c89b)

Here is the pdf being used:
[test_consignmentv2.pdf](https://github.com/o2solutions/pdf4net/files/14871523/test_consignmentv2.pdf)

I am using version 14.0.0.0 and using the netstandard2.0 assembly (O2S.Components.PDF4NET.NETStandard.dll). When using the .NET "Core" specific one (O2S.Components.PDF4NET.NET.dll) it gets better, but there are stille errors in the text.

Am I doing something wrong? It used to work with the old versions (5 and below).

**Comment by pdf4dev-solutions-support** [comment]
The PDF4NET evaluation assemblies replace random characters from extracted text with letters from 'PDF4NET'.
We tested the file you provided and the text is extracted correctly with the licensed version.

**Comment by FlipEX** [comment]
That makes sense. 
How do I get the licensed version? Previously we did it like this, but that doesn't work anymore:
`PDFDOc.SerialNumber = "SerialNumber_Here";`

**Comment by pdf4dev-solutions-support** [comment]
You have to upgrade your license to latest version. Please contact our support/sales by email for more details.
